#!/usr/bin/env php
<?php

require_once(__DIR__.'/../vendor/autoload.php');

use Symfony\Component\Console\Application;

$application = new Application('FrontController utility', '1.0.0');
$application->setCatchExceptions(false);
$application->add(new \FrontController\Command\ApacheConfGeneratorCommand());
$application->run();
